### ISSUE TITLE
Week 2 Assignment

### ISSUE THREAD

**Issue by navdeepkaurufl** [navdeepkaurufl/Agronomic-problems#2]
I faced some issues to make changes to the file already uploaded to the repository. So I have uploaded the new file named Grain_fiber_N_rate_trial_harvest_data_20210901.csv in order to make the data well structured. @brymz

**Comment by brymz** [comment]
Looks good, @navdeepkaurufl. Can you be more specific about the issues with uploading the new file? Were there error messages that you encountered?
