### ISSUE TITLE
Week-3-Assignment

### ISSUE THREAD

**Issue by navdeepkaurufl** [navdeepkaurufl/Agronomic-problems#3]
Statistical analysis to be done: @brymz
1. Analysis of variance for germination percentage, stand establishment, plant height, leaf tissue nutrient concentration, plant biomass, and seed yield based on the complete factorial design with four replication.
2. Analysis of variance for Normalized Difference Vegetation Index (NDVI) and Normalized Difference Infrared index and then establish a correlation between NDVI and NDRE with tissue nitrogen concentration, plant height, and yield.
3. Calculate gross return on yields at different nitrogen levels based on the hemp seed price.

**Comment by navdeepkaurufl** [comment]
The newly uploaded data include sensor data, emergence, stand establishment, plant height at 6 different dates, and the number of male and female plants in the measurement zone. The data uploaded matches the analysis plan. Additional required data has been uploaded and the wiki has been updated according to new data added.  

The new files which are added and the earlier data have been updated using terminal commands.

@brym I am done with this week's assignment.

**Comment by brymz** [comment]
Hi @navdeepkaurufl, This plan looks good. Certainly detailed enough to work through. This plan should be outlined in the analysis script you will be developing throughout the rest of the course. Consider the extra step of visualizing and checking the quality of your data prior to these analysis goals.
