### ISSUE TITLE
Week 4 and 5 assignment

### ISSUE THREAD

**Issue by navdeepkaurufl** [navdeepkaurufl/Agronomic-problems#4]
Hi @brymz, thanks for providing feedback about the week 3 assignment. I was wondering do I need to check if my data is normally distributed as a quality check or any other steps?
Also, according to the week 4 and week 5 assignments, I used all the R commands mentioned for data management and prepared R scripts for the three data files. I calculated the mean and standard deviation of all variables by grouping them and also used mutate command to calculate return to nitrogen. 
Would you please let me know if I am on right track or I need to make further changes to the data and R scripts?

**Comment by navdeepkaurufl** [comment]
Also, I was just concerned that this repository is public, do I need to make it private? Will you still be able to access this repository if I make it private?

**Comment by brymz** [comment]
Hi @navdeepkaurufl,
I am pleased to see your work here. I would recommend that you combine your summary files into a single script and consider how each of those files/steps may be replicated or "automated". We can cover some of these topics in later weeks along with best practices for formatting. I usually check for nomality through a visualization, but you are welcome to do other quality checks as well. I think this is a critical step of working with data.

**Comment by navdeepkaurufl** [comment]
Hi @brymz 
Thank you for providing your comments. I did everything in one R file and added new codes to the same R file. The results are replicable. I have uploaded the R file for harvest data, in-season data, and NDVI, on GitHub.  I will add normality test R codes into the data.

**Comment by brymz** [comment]
Perfect. I am generally supportive of public data and do not have concerns about this repo.
